import BaseIcon from '../../../base/BaseIcon';

/**
 * 页码
 * @param {} props 
 * @returns 
 */
export default function (props) {
    return (
        <BaseIcon
            {...props}
            icon='url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCAxNiAxNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGcgY2xpcC1wYXRoPSJ1cmwoI2NsaXAwXzE1XzQyOCkiPgo8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9InJnYigwLDAsMCwwKSIvPgo8cGF0aCBkPSJNMTQgMTZINFYySDEwTDE0IDZWMTZaIiBmaWxsPSJ3aGl0ZSIvPgo8cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTMgMEg5VjFIM0wzIDE0SDJWMVYwSDNaTTkgMy4wMDAwMVY3SDEzVjE1SDVWMy4wMDAwMUg5Wk0xNCAxNlY2TDEwIDJMNCAyLjAwMDAxVjE2SDE0Wk0xMCAzLjVMMTIuNSA2SDEwVjMuNVoiIGZpbGw9IiM2NjY2NjYiLz4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik04IDhWOUgxMFY4SDExVjlIMTJWMTBIMTFMMTEgMTJIMTJWMTNIMTFWMTRIMTBWMTNIOFYxNEg3TDcgMTNINlYxMkg3TDcgMTBINlY5SDdMNyA4SDhaTTEwIDEyTDEwIDEwSDhWMTJIMTBaIiBmaWxsPSIjMzY3RkM5Ii8+CjwvZz4KPGRlZnM+CjxjbGlwUGF0aCBpZD0iY2xpcDBfMTVfNDI4Ij4KPHJlY3Qgd2lkdGg9IjE2IiBoZWlnaHQ9IjE2IiBmaWxsPSJ3aGl0ZSIvPgo8L2NsaXBQYXRoPgo8L2RlZnM+Cjwvc3ZnPgo=)'
        ></BaseIcon>
    );
};
