import BaseIcon from '../base/BaseIcon';

/**
 * 粗外边框
 * @param {} props 
 * @returns 
 */
export default function (props) {
    return (
        <BaseIcon
            {...props}
            type='toone'
            icon='url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAYAAAA8AXHiAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAG5SURBVHic7d3BbQIxEEBREqWj7WWLpJetiZxyiRQfjL9wxHsFWAg+s9LIgtsNAAAAAAAAAAAAAAD29LH6wOM4HqvPpHdd19IWPlceBj+ERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJL5e/QJ+W30v6F3sdg9uu7B2cr/fhx/WeZ6+BH/wKCQhLBLCIiEsEsIiISwSwiJhjzVgTzXPxCIhLBLCIiEsEsIiISwSwiIhLBIWpAMu+s0zsUgIi4SwSAiLhLBICIuEsEjYYw3YU80zsUgIi4SwSAiLhLBICIuEsEgIi8SWC9IVF+yc8VomFglhkRAWCWGREBYJYZEQFonl+49n/3rDX57M2e19N7FICIuEsEgIi4SwSAiLhLBICIvElhf9dvEfL9jtwsQiISwSwiIhLBLCIiEsEsIiYY81YE81z8QiISwSwiIhLBLCIiEsEsIiISwSFqQDLvrNM7FICIuEsEgIi4SwSAiLhLBI2GMN2FPN2y6sZ3/ykD14FJIQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhAQAAAAAAAAAAAAAAb+UbNWk6lXhFa8UAAAAASUVORK5CYII=)'
        ></BaseIcon>
    );
}
