import BaseIcon from '../base/BaseIcon';

/**
 * 全边框
 * @param {} props 
 * @returns 
 */
export default function (props) {
    return (
        <BaseIcon
            {...props}
            type='toone'
            icon='url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAYAAAA8AXHiAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAF6SURBVHic7d3BCcJAFEXRr9hR+i8hNZmVWwWZK0bPKWBC4DKL2bwZAAAAAAAAAAAAAAD4TpfVB27bdl99Jr1935e2cF15GDwIi4SwSAiLhLBICIuEsEjcPv3B1e8lpVdvcr/0L6u5sUgIi4SwSAiLhLBICIuEsEgIi4SwSAiLhLBICIuEsEgIi4SwSAiLhLBICIuEsEgIi4SwSAiLhLBICIuEsEgIi4SwSAiLhLBICIuEsEgIi4SwSAiLhLBICIuEsEgIi4SwSAiLhLBICIuE6V5mxnQvJyEsEsIiISwSwiIhLBLCImG69wnTve9zY5EQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJ073MjOleTkJYJIRFQlgkhEVCWCSEBQAAAAAAAAAAAAAA/JUDs7Ec3nys49sAAAAASUVORK5CYII=)'
        ></BaseIcon>
    );
}
