const HEADERS = [
    {
        value: {
            left: '',
            center: '',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '(无)',
        text: '(无)',
    },
    {
        value: {
            left: '',
            center: '第 &P 页',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第 1 页',
        text: '第 1 页',
    },
    {
        value: {
            left: '',
            center: '第&P页，共&N页',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第1页，共?页',
        text: '第1页，共?页',
    },
    {
        value: {
            left: '',
            center: '&A',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '目录索引',
        text: '目录索引',
    },
    {
        value: {
            left: '机密',
            center: '&D',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '机密,2024/3/14,第1页',
        text: '机密,2024/3/14,第1页',
    },
    {
        value: {
            left: '',
            center: '&F',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '工作簿',
        text: '工作簿',
    },
    {
        value: {
            left: '',
            center: '&A',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '目录索引,第1页',
        text: '目录索引,第1页',
    },
    {
        value: {
            left: '&A',
            center: '机密',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '目录索引,机密,第1页',
        text: '目录索引,机密,第1页',
    },
    {
        value: {
            left: '',
            center: '&F',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '工作簿,第1页',
        text: '工作簿,第1页',
    },
    {
        value: {
            left: '',
            center: '第&P页',
            right: '&A',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第1页,目录索引',
        text: '第1页,目录索引',
    },
    {
        value: {
            left: '',
            center: '第&P页',
            right: '&D',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第1页,2024/3/14',
        text: '第1页,2024/3/14',
    },
    {
        value: {
            left: '',
            center: '制作人：&D',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '制作人：2024/3/14,第1页',
        text: '制作人：2024/3/14,第1页',
    },
];

const FOOTERS = [
    {
        value: {
            left: '',
            center: '',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '(无)',
        text: '(无)',
    },
    {
        value: {
            left: '',
            center: '第 &P 页',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第 1 页',
        text: '第 1 页',
    },
    {
        value: {
            left: '',
            center: '第&P页，共&N页',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第1页，共?页',
        text: '第1页，共?页',
    },
    {
        value: {
            left: '',
            center: '&A',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '目录索引',
        text: '目录索引',
    },
    {
        value: {
            left: '机密',
            center: '&D',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '机密,2024/3/14,第1页',
        text: '机密,2024/3/14,第1页',
    },
    {
        value: {
            left: '',
            center: '&F',
            right: '',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '工作簿',
        text: '工作簿',
    },
    {
        value: {
            left: '',
            center: '&A',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '目录索引,第1页',
        text: '目录索引,第1页',
    },
    {
        value: {
            left: '&A',
            center: '机密',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '目录索引,机密,第1页',
        text: '目录索引,机密,第1页',
    },
    {
        value: {
            left: '',
            center: '&F',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '工作簿,第1页',
        text: '工作簿,第1页',
    },
    {
        value: {
            left: '',
            center: '第&P页',
            right: '&A',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第1页,目录索引',
        text: '第1页,目录索引',
    },
    {
        value: {
            left: '',
            center: '第&P页',
            right: '&D',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '第1页,2024/3/14',
        text: '第1页,2024/3/14',
    },
    {
        value: {
            left: '',
            center: '制作人：&D',
            right: '第&P页',
            leftImage: '',
            centerImage: '',
            rightImage: '',
        },
        title: '制作人：2024/3/14,第1页',
        text: '制作人：2024/3/14,第1页',
    },
];

export const getHeaders = function () {};
