export default function () {
    return (
        <svg
            width='140px'
            height='140px'
            viewBox='0 0 140 140'
            version='1.1'
            xmlns='http://www.w3.org/2000/svg'
            xmlnsXlink='http://www.w3.org/1999/xlink'
            style={{ height: '100%', width: '100%', fill: '#217346' }}
        >
            <defs>
                <circle id='path-1' cx='70' cy='70' r='70'></circle>
                <linearGradient
                    x1='0%'
                    y1='49.9965104%'
                    x2='12.2497876%'
                    y2='50%'
                    id='linearGradient-3'
                >
                    <stop stopColor='#D0D0D0' offset='0%'></stop>
                    <stop stopColor='#999999' offset='100%'></stop>
                </linearGradient>
                <linearGradient
                    x1='50%'
                    y1='0%'
                    x2='50%'
                    y2='7.47826316%'
                    id='linearGradient-4'
                >
                    <stop stopColor='#CECECE' offset='0.0865589489%'></stop>
                    <stop stopColor='#9C9C9C' offset='100%'></stop>
                </linearGradient>
            </defs>
            <g
                id='row-based-report'
                stroke='none'
                strokeWidth='1'
                fill='none'
                fillRule='evenodd'
            >
                <g id='编组-10'>
                    <g id='编组-2'>
                        <mask id='mask-2' fill='white'>
                            <use xlinkHref='#path-1'></use>
                        </mask>
                        <use id='蒙版' fill='white' xlinkHref='#path-1'></use>
                        <g mask='url(#mask-2)'>
                            <g transform='translate(8.000000, 30.000000)'>
                                <g
                                    id='编组'
                                    strokeWidth='1'
                                    fill='none'
                                    fillRule='evenodd'
                                    transform='translate(0.396380, 0.000000)'
                                >
                                    <rect
                                        id='矩形'
                                        fill='#E6E6E6'
                                        x='0.990949997'
                                        y='0.920167855'
                                        width='138.13843'
                                        height='87.0620355'
                                    ></rect>
                                    <rect
                                        id='矩形'
                                        fill='#FFFFFF'
                                        x='0.396379999'
                                        y='0.38222357'
                                        width='138.733'
                                        height='87.2035998'
                                    ></rect>
                                    <rect
                                        id='矩形'
                                        fill='#D9E3F2'
                                        x='0.396379999'
                                        y='0.38222357'
                                        width='138.733'
                                        height='8.32397998'
                                    ></rect>
                                    <polygon
                                        id='矩形'
                                        fill='url(#linearGradient-3)'
                                        points='0.178371 0.38222357 139.12938 0.38222357 139.12938 0.778603569 0.178371 0.778603569'
                                    ></polygon>
                                    <rect
                                        id='矩形'
                                        fill='url(#linearGradient-4)'
                                        x='0'
                                        y='0.396379999'
                                        width='1'
                                        height='87.0620355'
                                    ></rect>
                                    <polygon
                                        id='矩形备份'
                                        fill='#000000'
                                        points='0.368302592 8.30982355 139.12938 8.30982355 139.12938 8.70620355 0.368302592 8.70620355'
                                    ></polygon>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='24.1650235'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份-9'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='16.2374235'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='32.0926235'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='40.0202235'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='47.9478234'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='55.8754234'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='63.8030234'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='71.7306234'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='79.6582234'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形备份'
                                        fill='#DFE8E8'
                                        x='0.396379999'
                                        y='87.5858233'
                                        width='138.733'
                                        height='1'
                                    ></rect>
                                    <rect
                                        id='矩形'
                                        fill='#DFE8E8'
                                        x='38.8452399'
                                        y='8.70620355'
                                        width='1'
                                        height='78.8796198'
                                    ></rect>
                                    <rect
                                        id='矩形备份-4'
                                        fill='#DFE8E8'
                                        x='75.7085798'
                                        y='8.70620355'
                                        width='1'
                                        height='78.8796198'
                                    ></rect>
                                    <rect
                                        id='矩形备份-5'
                                        fill='#DFE8E8'
                                        x='97.9058598'
                                        y='8.70620355'
                                        width='1'
                                        height='78.8796198'
                                    ></rect>
                                    <rect
                                        id='矩形备份-6'
                                        fill='#DFE8E8'
                                        x='120.10314'
                                        y='8.70620355'
                                        width='1'
                                        height='78.8796198'
                                    ></rect>
                                </g>
                                <rect
                                    id='矩形备份-13'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='19.8048435'
                                    width='21.4045199'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-22'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='58.2678599'
                                    y='19.8048435'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-26'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='80.4651398'
                                    y='27.7324435'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-27'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='88.3927398'
                                    y='42.7948835'
                                    width='7.92759998'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-28'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='80.4651398'
                                    y='51.1188634'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-29'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='111.38278'
                                    y='58.6500834'
                                    width='7.92759998'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-30'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='103.45518'
                                    y='35.2636635'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-45'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='103.45518'
                                    y='11.8772435'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-31'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='103.45518'
                                    y='74.5052834'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-32'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='27.3360635'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-34'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='35.2636635'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-46'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='11.8772435'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-35'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='42.7948835'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-36'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='50.7224834'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-37'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='58.2537034'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-38'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='67.3704434'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-39'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='74.1089034'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-33'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='128.03074'
                                    y='19.8048435'
                                    width='9.90949997'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-23'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='62.2316598'
                                    y='35.6600435'
                                    width='11.8914'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-47'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='62.2316598'
                                    y='12.2736235'
                                    width='11.8914'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-24'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='58.2678599'
                                    y='42.7948835'
                                    width='15.8552'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-25'
                                    fill='#8E8E8E'
                                    fillRule='evenodd'
                                    x='88.3927398'
                                    y='19.8048435'
                                    width='7.92759998'
                                    height='1'
                                ></rect>
                                <rect
                                    id='矩形备份-14'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='27.7324435'
                                    width='15.8552'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-15'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='35.6600435'
                                    width='19.8189999'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-48'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='12.2736235'
                                    width='19.8189999'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-16'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='43.5876435'
                                    width='23.7827999'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-17'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='51.5152434'
                                    width='17.8371'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-18'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='59.4428434'
                                    width='23.7827999'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-19'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='67.3704434'
                                    width='11.8914'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-20'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='75.2980434'
                                    width='15.8552'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-21'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='83.2256434'
                                    width='31.7103999'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-40'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='55.0968199'
                                    y='83.2256434'
                                    width='17.8371'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-41'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='83.6361798'
                                    y='83.2256434'
                                    width='12.68416'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-42'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='106.62622'
                                    y='83.2256434'
                                    width='12.68416'
                                    height='1.18914'
                                ></rect>
                                <rect
                                    id='矩形备份-8'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='41.2235199'
                                    y='3.15688356'
                                    width='25.3683199'
                                    height='2.37827999'
                                ></rect>
                                <rect
                                    id='矩形备份-43'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='2.37827999'
                                    y='3.15688356'
                                    width='25.3683199'
                                    height='2.37827999'
                                ></rect>
                                <rect
                                    id='矩形备份-10'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='77.6904798'
                                    y='3.15688356'
                                    width='13.8733'
                                    height='2.37827999'
                                ></rect>
                                <rect
                                    id='矩形备份-11'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='99.8877597'
                                    y='3.15688356'
                                    width='13.8733'
                                    height='2.37827999'
                                ></rect>
                                <rect
                                    id='矩形备份-12'
                                    fill='#727272'
                                    fillRule='evenodd'
                                    x='122.08504'
                                    y='3.15688356'
                                    width='11.8914'
                                    height='2.37827999'
                                ></rect>
                                <path
                                    d='M40.4307599,39.2274635 L40.4307599,41.2093635 L38.4488599,41.2093635 L38.4488599,39.2274635 L40.4307599,39.2274635 Z M40.0343799,31.6962435 L40.034,38.8302435 L39.241,38.8302435 L39.2416199,32.4890035 L0.792759998,32.4890035 L0.792759998,40.0202235 L38.052,40.0192435 L38.052,40.8122435 L0,40.8129835 L0,31.6962435 L40.0343799,31.6962435 Z'
                                    id='形状结合'
                                    fill='#217346'
                                    fillRule='nonzero'
                                ></path>
                            </g>
                        </g>
                    </g>
                    <g id='编组-6' transform='translate(100.000000, 95.000000)'>
                        <rect
                            id='矩形'
                            fill='#217345'
                            x='0'
                            y='0'
                            width='40'
                            height='40'
                            rx='7'
                        ></rect>
                        <rect
                            id='矩形'
                            fill='#F5F5F5'
                            x='4'
                            y='7'
                            width='5'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-51'
                            fill='#F5F5F5'
                            x='4'
                            y='15'
                            width='5'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-54'
                            fill='#F5F5F5'
                            x='4'
                            y='23'
                            width='5'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-57'
                            fill='#F5F5F5'
                            x='4'
                            y='31'
                            width='5'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-49'
                            fill='#F5F5F5'
                            x='11'
                            y='7'
                            width='14'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-52'
                            fill='#F5F5F5'
                            x='11'
                            y='15'
                            width='14'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-55'
                            fill='#F5F5F5'
                            x='11'
                            y='23'
                            width='14'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-58'
                            fill='#F5F5F5'
                            x='11'
                            y='31'
                            width='14'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-50'
                            fill='#F5F5F5'
                            x='27'
                            y='7'
                            width='9'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-53'
                            fill='#F5F5F5'
                            x='27'
                            y='15'
                            width='9'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-56'
                            fill='#F5F5F5'
                            x='27'
                            y='23'
                            width='9'
                            height='3'
                            rx='1'
                        ></rect>
                        <rect
                            id='矩形备份-59'
                            fill='#F5F5F5'
                            x='27'
                            y='31'
                            width='9'
                            height='3'
                            rx='1'
                        ></rect>
                    </g>
                </g>
            </g>
        </svg>
    );
}
