datasource = {
    dataSourceDefinition: [
        {
            id: 'projectName',
            type: 'text',
            typeName: '文本',
            desc: '项目名称',
            code: 'projectName',
            name: '项目名称',
        },
        {
            id: 'contractName',
            type: 'text',
            typeName: '文本',
            desc: '承包单位',
            code: 'contractName',
            name: '承包单位',
        },
        {
            id: 'contractCode',
            type: 'text',
            typeName: '文本',
            desc: '合同编号',
            code: 'contractCode',
            name: '合同编号',
        },
        {
            id: 'constructionName',
            type: 'text',
            typeName: '文本',
            desc: '监理单位',
            code: 'constructionName',
            name: '监理单位',
        },
        {
            id: 'period',
            type: 'text',
            typeName: '文本',
            desc: '期次',
            code: 'period',
            name: '期次',
        },
        {
            id: 'expirationDate',
            type: 'text',
            typeName: '文本',
            desc: '截止日期',
            code: 'expirationDate',
            name: '截止日期',
        },
        {
            id: 'contractPerson',
            type: 'text',
            typeName: '文本',
            desc: '承包人',
            code: 'expirationDate',
            name: '承包人',
        },
        {
            id: 'contractDate',
            type: 'text',
            typeName: '文本',
            desc: '承包人承包日期',
            code: 'contractDate',
            name: '承包人承包日期',
        },
        {
            id: 'constructionPerson',
            type: 'text',
            typeName: '文本',
            desc: '监理工程师',
            code: 'constructionPerson',
            name: '监理工程师',
        },
        {
            id: 'constructionPersonDate',
            type: 'text',
            typeName: '文本',
            desc: '监理日期',
            code: 'constructionPersonDate',
            name: '监理日期',
        },
        {
            id: 'chief',
            type: 'text',
            typeName: '文本',
            desc: '总监',
            code: 'chief',
            name: '总监',
        },
        {
            id: 'chiefDate',
            type: 'text',
            typeName: '文本',
            desc: '总监日期',
            code: 'chiefDate',
            name: '总监日期',
        },
        {
            id: 'proprietor',
            type: 'text',
            typeName: '文本',
            desc: '业主',
            code: 'proprietor',
            name: '业主',
        },
        {
            id: 'proprietorDate',
            type: 'text',
            typeName: '文本',
            desc: '业主日期',
            code: 'proprietorDate',
            name: '业主日期',
        },
        {
            id: 'payDetail',
            type: 'table',
            typeName: '表',
            desc: '支付详细',
            code: 'payDetail',
            name: '支付详细',
            children: [
                {
                    id: 'code',
                    type: 'text',
                    typeName: '文本',
                    desc: '清单编号',
                    code: 'code',
                    name: '清单编号',
                },{
                    id: 'projectName',
                    type: 'text',
                    typeName: '文本',
                    desc: '项目名称',
                    code: 'projectName',
                    name: '项目名称',
                },{
                    id: 'unit',
                    type: 'text',
                    typeName: '文本',
                    desc: '单位',
                    code: 'unit',
                    name: '单位',
                },{
                    id: 'contractCount',
                    type: 'integer',
                    typeName: '整数',
                    desc: '原合同数据量',
                    code: 'contractCount',
                    name: '原合同数据量',
                },{
                    id: 'contractPrice',
                    type: 'decimals',
                    typeName: '小数',
                    desc: '原合同单价',
                    code: 'contractPrice',
                    name: '原合同单价',
                },{
                    id: 'contractChanged',
                    type: 'integer',
                    typeName: '整数',
                    desc: '变更后数量',
                    code: 'contractChanged',
                    name: '变更后数量',
                },{
                    id: 'bqmCount',
                    type: 'integer',
                    typeName: '整数',
                    desc: '本期末完成数量',
                    code: 'bqmCount',
                    name: '本期末完成数量',
                },{
                    id: 'bqmSum',
                    type: 'decimals',
                    typeName: '小数',
                    desc: '本期末完成金额',
                    code: 'contractPrice',
                    name: '本期末完成金额',
                },{
                    id: 'sqmCount',
                    type: 'integer',
                    typeName: '整数',
                    desc: '上期末完成数量',
                    code: 'sqmCount',
                    name: '上期末完成数量',
                },{
                    id: 'sqmSum',
                    type: 'decimals',
                    typeName: '小数',
                    desc: '上期末完成金额',
                    code: 'sqmSum',
                    name: '上期末完成金额',
                },{
                    id: 'bqCount',
                    type: 'integer',
                    typeName: '整数',
                    desc: '本期完成数量',
                    code: 'bqCount',
                    name: '本期完成数量',
                },{
                    id: 'bqSum',
                    type: 'decimals',
                    typeName: '小数',
                    desc: '本期完成金额',
                    code: 'bqSum',
                    name: '本期完成金额',
                }
            ],
        },
    ], //数据源定义
    datas: {
        projectName: '安兴高速',
        contractName:'中铁十五局',
        contractCode: 'CON-AXGS-20240101001',
        constructionName:'四川恒远工程建设监理有限公司',
        period:'第一期',
        expirationDate:'2024-02-16',
        contractPerson:'张胜',
        contractDate:'2024-01-25',
        constructionPerson:'李响',
        constructionPersonDate:'2024-01-25',
        chief:'王立',
        chiefDate:'2024-01-25',
        proprietor:'汪宏',
        proprietorDate:'2024-01-25',
        payDetail:[{
            code:'300',
            projectName:'路面',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:100000,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:100000,
        },{
            code:'302-1',
            projectName:'垫层',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:50000,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:50000,
        },{
            code:'302-1-1',
            projectName:'碎石垫层',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:50000,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:50000,
        },{
            code:'302-1-1-1',
            projectName:'碎石垫层',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:50000,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:50000,
        },{
            code:'302-1-1-1-1',
            projectName:'厚150mm以内',
            unit:'m2',
            contractCount:20,
            contractPrice:10000,
            contractChanged:20,
            bqmCount:5,
            bqmSum:50000,
            sqmCount:0,
            sqmSum:0,
            bqCount:5,
            bqSum:50000,
        },{
            code:'302-1-1-1-2',
            projectName:'厚150mm以内',
            unit:'m2',
            contractCount:20,
            contractPrice:10000,
            contractChanged:20,
            bqmCount:0,
            bqmSum:0,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:0,
        },{
            code:'308-1',
            projectName:'透层',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:50000,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:50000,
        },{
            code:'308-1-2',
            projectName:'透层（阴离子乳化沥青）',
            unit:'m2',
            contractCount:30,
            contractPrice:10000,
            contractChanged:5,
            bqmCount:50000,
            bqmSum:50000,
            sqmCount:0,
            sqmSum:0,
            bqCount:5,
            bqSum:50000,
        },{
            code:'308-2',
            projectName:'黏层',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:0,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:0,
        },{
            code:'308-2-2',
            projectName:'改性乳化沥青粘层',
            unit:'m2',
            contractCount:30,
            contractPrice:10000,
            contractChanged:30,
            bqmCount:0,
            bqmSum:0,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:0,
        },{
            code:'311-1',
            projectName:'细粒式改性沥青混合料',
            unit:'',
            contractCount:0,
            contractPrice:0,
            contractChanged:0,
            bqmCount:0,
            bqmSum:0,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:0,
        },{
            code:'311-1-a',
            projectName:'厚40mm',
            unit:'m2',
            contractCount:0,
            contractPrice:100,
            contractChanged:0,
            bqmCount:0,
            bqmSum:0,
            sqmCount:0,
            sqmSum:0,
            bqCount:0,
            bqSum:0,
        }],
    }, //数据源数据
    allowToView: true, //是否允许查看数据源
    allowToEdit: false, //是否允许编辑数据源
};
