import { parseDefine } from './utils';

const define = {
    metadata: {
        code: 'Ipes_MP_Middlepaysummary_DetailCalc',
        name: '中间计量支付汇总表',
        children: [
            {
                field: 'billCode',
                dataType: 'java.lang.String',
                fieldName: '清单编号',
            },
            {
                field: 'billName',
                dataType: 'java.lang.String',
                fieldName: '清单名称',
            },
            {
                field: 'code',
                dataType: 'java.lang.String',
                fieldName: '凭证号',
            },
            {
                field: 'billUnit',
                dataType: 'java.lang.String',
                fieldName: '清单单位',
            },
            {
                field: 'payQuantity',
                dataType: 'java.lang.Double',
                fieldName: '支付数量',
            },
            {
                field: 'billUnitprice',
                dataType: 'java.lang.Double',
                fieldName: '清单单价',
            },
            {
                field: 'payMoney',
                dataType: 'java.lang.Double',
                fieldName: '支付金额',
            },
            {
                field: 'dataIndex',
                dataType: 'int',
                fieldName: 'dataIndex',
            },
            {
                field: 'emptyRow',
                dataType: 'java.lang.Boolean',
                fieldName: 'emptyRow',
            },
            {
                field: 'groupId',
                dataType: 'java.lang.String',
                fieldName: 'groupId',
            },
            {
                field: 'totalRow',
                dataType: 'java.lang.Boolean',
                fieldName: 'totalRow',
            },
        ],
    },
    datas: [
        {
            dataIndex: 1,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '302-1-1-1-1',
            billName: '厚150mm以内',
            code: '',
            billUnit: 'm2',
            payQuantity: 2,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 2,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-011',
            billUnit: '',
            payQuantity: 2,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 3,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '302-1-1-1',
            billName: '厚150mm以内',
            code: '',
            billUnit: 'm2',
            payQuantity: 18047,
            billUnitprice: 46.95,
            payMoney: 847306.65,
        },
        {
            dataIndex: 4,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-001',
            billUnit: '',
            payQuantity: 6500,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 5,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-002',
            billUnit: '',
            payQuantity: 3000,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 6,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-005',
            billUnit: '',
            payQuantity: 2045,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 7,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-008',
            billUnit: '',
            payQuantity: 6500,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 8,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-011',
            billUnit: '',
            payQuantity: 2,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 9,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '302-1-1-2',
            billName: '厚150mm以内',
            code: '',
            billUnit: 'm2',
            payQuantity: 11962,
            billUnitprice: 41.74,
            payMoney: 499293.88,
        },
        {
            dataIndex: 10,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-003',
            billUnit: '',
            payQuantity: 2000,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 11,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-004',
            billUnit: '',
            payQuantity: 6950,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 12,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-006',
            billUnit: '',
            payQuantity: 1535,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 13,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-007',
            billUnit: '',
            payQuantity: 1332,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 14,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-009',
            billUnit: '',
            payQuantity: 65,
            billUnitprice: 0,
            payMoney: 0,
        },
        {
            dataIndex: 15,
            emptyRow: false,
            groupId: '',
            totalRow: false,
            billCode: '',
            billName: '',
            code: 'SG01-JLQ01-010',
            billUnit: '',
            payQuantity: 80,
            billUnitprice: 0,
            payMoney: 0,
        },
    ],
};

export default parseDefine(define);