import { parseDefine } from './utils';

/**
 * 中期支付证书数据源
 */
const define = {
    "metadata": {
        "code": "Ipes_MP_Certificate_DetailCalc",
        "name": "中期支付证书",
        "children": [
            {
                "field": "yy",
                "dataType": "java.lang.String",
                "fieldName": "类别"
            },
            {
                "field": "itemno",
                "dataType": "java.lang.String",
                "fieldName": "清单号"
            },
            {
                "field": "itemname",
                "dataType": "java.lang.String",
                "fieldName": "项目内容"
            },
            {
                "field": "htamt",
                "dataType": "java.lang.Double",
                "fieldName": "原有总金额"
            },
            {
                "field": "bgamt",
                "dataType": "java.lang.Double",
                "fieldName": "变更总金额"
            },
            {
                "field": "bghamt",
                "dataType": "java.lang.Double",
                "fieldName": "变更后总金额"
            },
            {
                "field": "bqmamt",
                "dataType": "java.lang.Double",
                "fieldName": "本期末金额"
            },
            {
                "field": "sqmamt",
                "dataType": "java.lang.Double",
                "fieldName": "上期末金额"
            },
            {
                "field": "bqamt",
                "dataType": "java.lang.Double",
                "fieldName": "本期金额"
            },
            {
                "field": "dataIndex",
                "dataType": "int",
                "fieldName": "dataIndex"
            },
            {
                "field": "emptyRow",
                "dataType": "java.lang.Boolean",
                "fieldName": "emptyRow"
            },
            {
                "field": "groupId",
                "dataType": "java.lang.String",
                "fieldName": "groupId"
            },
            {
                "field": "totalRow",
                "dataType": "java.lang.Boolean",
                "fieldName": "totalRow"
            }
        ]
    },
    "datas": [
        {
            "dataIndex": 1,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "200",
            "itemname": "矿山开拓工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 2,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "100",
            "itemname": "总则 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 3,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "300",
            "itemname": "道路及附属工程",
            "htamt": 655954636,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 1346506.63,
            "sqmamt": 0,
            "bqamt": 1346506.63
        },
        {
            "dataIndex": 4,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "400",
            "itemname": "桥涵工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 5,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "500",
            "itemname": "生产线工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 6,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "600",
            "itemname": "建筑工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 7,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "700",
            "itemname": "绿化工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 8,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "800",
            "itemname": "机电工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 9,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "暂计款 ",
            "itemname": "暂计款 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 10,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "优化分成",
            "itemname": "优化分成",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 11,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "300-1",
            "itemname": "300章 路面工程",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 12,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "清单小计（涉及暂扣项小计） ",
            "itemname": "清单小计（涉及暂扣项小计） ",
            "htamt": 655954636,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 1346506.63,
            "sqmamt": 0,
            "bqamt": 1346506.63
        },
        {
            "dataIndex": 13,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "暂列金额",
            "itemname": "暂列金额",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 14,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "设计费",
            "itemname": "设计费",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 15,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "清单计量小计",
            "itemname": "清单计量小计",
            "htamt": 655954636,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 1346506.63,
            "sqmamt": 0,
            "bqamt": 1346506.63
        },
        {
            "dataIndex": 16,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "价格调整",
            "itemname": "价格调整",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 17,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "索赔金额 ",
            "itemname": "索赔金额 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 18,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "违约罚金",
            "itemname": "违约罚金",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 19,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "迟付款利息 ",
            "itemname": "迟付款利息 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 20,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "奖罚金",
            "itemname": "奖罚金",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 21,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "甲供材扣回",
            "itemname": "甲供材扣回",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 22,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "合计",
            "itemname": "合计",
            "htamt": 655954636,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 1346506.63,
            "sqmamt": 0,
            "bqamt": 1346506.63
        },
        {
            "dataIndex": 23,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "开工预付款 ",
            "itemname": "开工预付款 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 20909117.66,
            "sqmamt": 0,
            "bqamt": 20909117.66
        },
        {
            "dataIndex": 24,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "预付款扣款 ",
            "itemname": "预付款扣款 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 25,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "计量暂扣款",
            "itemname": "计量暂扣款",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 26,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "质量保证金 ",
            "itemname": "质量保证金 ",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 27,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "返还计量暂扣款",
            "itemname": "返还计量暂扣款",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 28,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "甲供材扣回",
            "itemname": "甲供材扣回",
            "htamt": 0,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 0,
            "sqmamt": 0,
            "bqamt": 0
        },
        {
            "dataIndex": 29,
            "emptyRow": false,
            "groupId": "",
            "totalRow": false,
            "yy": null,
            "itemno": "实际支付",
            "itemname": "实际支付",
            "htamt": 655954636,
            "bgamt": 0,
            "bghamt": 0,
            "bqmamt": 22255624.29,
            "sqmamt": 0,
            "bqamt": 22255624.29
        }
    ]
}

export default parseDefine(define);
