import BaseIcon from '../../../base/BaseIcon';

/**
 * 纸张方向
 * @param {} props 
 * @returns 
 */
export default function (props) {
    return (
        <BaseIcon
            {...props}
            icon='url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIiBmaWxsPSJyZ2IoMCwwLDAsMCkiLz4KPHBhdGggZD0iTTE5IDI0SDFWMEgxMi44MTI1TDE5IDYuNlYyNFoiIGZpbGw9IndoaXRlIi8+CjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMTIuMzEyNSAxVjcuMUgxOFYxM0gxOVY2LjZMMTIuODEyNSAwSDFWMjRIN1YyM0gyVjFIMTIuMzEyNVpNMTMuMzEyNSAxLjk5NTQ1TDE3LjE2MDUgNi4xSDEzLjMxMjVWMS45OTU0NVoiIGZpbGw9IiM2NjY2NjYiLz4KPHBhdGggZD0iTTggMTRMOCAzMkwzMiAzMkwzMiAyMC4xODc1TDI1LjQgMTRMOCAxNFoiIGZpbGw9IndoaXRlIi8+CjxwYXRoIGQ9Ik04IDE0TDggMzJMMzIgMzJMMzIgMjAuMTg3NUwyNS40IDE0TDggMTRaIiBmaWxsPSJ3aGl0ZSIvPgo8cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0LjkgMjAuNjg3NUwzMSAyMC42ODc1TDMxIDMxTDkgMzFMOSAxNUwyNC45IDE1TDI0LjkgMjAuNjg3NVpNMjUuNCAxNEw4IDE0TDggMzJMMzIgMzJMMzIgMjAuMTg3NUwyNS40IDE0Wk0yNS45IDE1LjgzOTVMMzAuMDA0NiAxOS42ODc1TDI1LjkgMTkuNjg3NUwyNS45IDE1LjgzOTVaIiBmaWxsPSIjNjY2NjY2Ii8+Cjwvc3ZnPgo=)'
        ></BaseIcon>
    );
};
