/**
 * 计量支付-中期证书
 */

export default {
    name:"计量支付-中期证书[jlzf/zqzf.js]",
    template:{
        version: '17.0.5',
        name: '',
        docProps: {
            docPropsCore: {
                creator: 'Matoah Steven',
                lastModifiedBy: 'Matoah Steven',
                created: '2024-04-18T05:29:13Z',
                modified: '2024-04-23T02:59:28Z',
            },
            docPropsApp: {
                Application: 'Microsoft Excel',
                DocSecurity: '0',
                ScaleCrop: 'false',
                HeadingPairs: {
                    size: 2,
                    baseType: 'variant',
                    workbookInfoArray: [
                        {
                            elementType: 'vt:lpstr',
                            value: '工作表',
                        },
                        {
                            elementType: 'vt:i4',
                            value: '1',
                        },
                    ],
                },
                TitlesOfParts: {
                    size: 1,
                    baseType: 'lpstr',
                    sheetsNameArray: ['Ipes_MP_Certificate'],
                },
                LinksUpToDate: 'false',
                SharedDoc: 'false',
                HyperlinksChanged: 'false',
                AppVersion: '16.0300',
            },
        },
        sheetCount: 1,
        tabStripRatio: 0.6,
        iterativeCalculation: false,
        iterativeCalculationMaximumIterations: 100,
        iterativeCalculationMaximumChange: 0.001,
        customList: [],
        defaultSheetTabStyles: {},
        sheets: {
            Ipes_MP_Certificate: {
                name: 'Ipes_MP_Certificate',
                isSelected: true,
                rowCount: 9,
                columnCount: 9,
                visible: 1,
                theme: {
                    name: 'Office',
                    themeColor: {
                        name: 'Office',
                        background1: {
                            a: 255,
                            r: 255,
                            g: 255,
                            b: 255,
                        },
                        background2: {
                            a: 255,
                            r: 231,
                            g: 230,
                            b: 230,
                        },
                        text1: {
                            a: 255,
                            r: 0,
                            g: 0,
                            b: 0,
                        },
                        text2: {
                            a: 255,
                            r: 68,
                            g: 84,
                            b: 106,
                        },
                        accent1: {
                            a: 255,
                            r: 68,
                            g: 114,
                            b: 196,
                        },
                        accent2: {
                            a: 255,
                            r: 237,
                            g: 125,
                            b: 49,
                        },
                        accent3: {
                            a: 255,
                            r: 165,
                            g: 165,
                            b: 165,
                        },
                        accent4: {
                            a: 255,
                            r: 255,
                            g: 192,
                            b: 0,
                        },
                        accent5: {
                            a: 255,
                            r: 91,
                            g: 155,
                            b: 213,
                        },
                        accent6: {
                            a: 255,
                            r: 112,
                            g: 173,
                            b: 71,
                        },
                        hyperlink: {
                            a: 255,
                            r: 5,
                            g: 99,
                            b: 193,
                        },
                        followedHyperlink: {
                            a: 255,
                            r: 149,
                            g: 79,
                            b: 114,
                        },
                    },
                    headingFont: "'Calibri Light'",
                    bodyFont: 'Calibri',
                    font: {
                        headerFont: "'Calibri Light'",
                        bodyFont: 'Calibri',
                    },
                },
                data: {
                    dataTable: {
                        0: {
                            0: {
                                value: '[项目参数计算器.项目名称]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle18',
                                },
                                bindingPath: 'IP_Project_ParamCalc.project_name2',
                                tag: '{"instanceId":"jo77j2a7ngoyymt22h3s4glqw5buge6flvw19mo5","bindInfo":{"bindType":"cell","bindDsInstanceId":"project_name2"}}',
                            },
                            1: {
                                style: '__builtInStyle18',
                            },
                            2: {
                                style: '__builtInStyle18',
                            },
                            3: {
                                style: '__builtInStyle18',
                            },
                            4: {
                                style: '__builtInStyle18',
                            },
                            5: {
                                style: '__builtInStyle18',
                            },
                            6: {
                                style: '__builtInStyle18',
                            },
                            7: {
                                style: '__builtInStyle18',
                            },
                            8: {
                                style: '__builtInStyle18',
                            },
                        },
                        1: {
                            0: {
                                value: '中 期 支 付 证 书',
                                style: '__builtInStyle18',
                            },
                            1: {
                                style: '__builtInStyle18',
                            },
                            2: {
                                style: '__builtInStyle18',
                            },
                            3: {
                                style: '__builtInStyle18',
                            },
                            4: {
                                style: '__builtInStyle18',
                            },
                            5: {
                                style: '__builtInStyle18',
                            },
                            6: {
                                style: '__builtInStyle18',
                            },
                            7: {
                                style: '__builtInStyle18',
                            },
                            8: {
                                style: '__builtInStyle18',
                            },
                        },
                        2: {
                            0: {
                                value: '承包单位：',
                                style: '__builtInStyle2',
                            },
                            1: {
                                value: '[合同参数计算器.乙方公司]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle16',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_partybEnterprise',
                                tag: '{"instanceId":"430km1weje25excznowxwkslr3lurrfhrlvw1a5qb","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_partybEnterprise"}}',
                            },
                            2: {
                                style: '__builtInStyle16',
                            },
                            3: {
                                value: '合同编号：',
                                style: '__builtInStyle6',
                            },
                            4: {
                                value: '[合同参数计算器.合同编码]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle11',
                                },
                                bindingPath: 'IP_Contract_ParamCalc.contract_code',
                                tag: '{"instanceId":"8ofhggf0pi5rjfduz41rachk2nt3hyelvw1ah23","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_code"}}',
                            },
                            5: {
                                style: '__builtInStyle11',
                            },
                            6: {
                                style: '__builtInStyle3',
                            },
                            7: {
                                style: '__builtInStyle3',
                            },
                            8: {
                                style: '__builtInStyle3',
                            },
                        },
                        3: {
                            0: {
                                value: '监理单位：',
                                style: '__builtInStyle2',
                            },
                            1: {
                                value: '[合同参数计算器.工人方企业]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle17',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_workerPartybEnterprise',
                                tag: '{"instanceId":"k5s263qbp5iakbx5hs14iboldsh0uxplqlvw1ace7","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_workerPartybEnterprise"}}',
                            },
                            2: {
                                style: '__builtInStyle17',
                            },
                            3: {
                                value: '期次：',
                                style: '__builtInStyle6',
                            },
                            4: {
                                value: '[期次参数计算器.期次名称]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle15',
                                },
                                bindingPath:
                                    'IP_ContPeriods_ParamCalc.contPeriods_contPeriodsName',
                                tag: '{"instanceId":"7rlzg6d10wfx85lyhch18swjcyggar268lvw1am73","bindInfo":{"bindType":"cell","bindDsInstanceId":"contPeriods_contPeriodsName"}}',
                            },
                            5: {
                                style: '__builtInStyle15',
                            },
                            6: {
                                value: '截止日期：',
                                style: '__builtInStyle6',
                            },
                            7: {
                                value: '[合同参数计算器.签订日期]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle15',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_signDate',
                                tag: '{"instanceId":"3ayb3khcc6nhhnchgeshefwm7c9ze5falvw1b03n","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_signDate"}}',
                            },
                            8: {
                                style: '__builtInStyle15',
                            },
                        },
                        4: {
                            0: {
                                value: '清单号',
                                style: '__builtInStyle14',
                            },
                            1: {
                                style: '__builtInStyle14',
                            },
                            2: {
                                value: '项目内容',
                                style: '__builtInStyle14',
                            },
                            3: {
                                value: '合同价及变更金额',
                                style: '__builtInStyle14',
                            },
                            4: {
                                style: '__builtInStyle14',
                            },
                            5: {
                                style: '__builtInStyle14',
                            },
                            6: {
                                value: '到本期末完成',
                                style: '__builtInStyle14',
                            },
                            7: {
                                value: '到上期末完成',
                                style: '__builtInStyle14',
                            },
                            8: {
                                value: '本期完成',
                                style: '__builtInStyle14',
                            },
                        },
                        5: {
                            0: {
                                style: '__builtInStyle14',
                            },
                            1: {
                                style: '__builtInStyle14',
                            },
                            2: {
                                style: '__builtInStyle14',
                            },
                            3: {
                                value: '合同总金额',
                                style: '__builtInStyle5',
                            },
                            4: {
                                value: '变更总金额',
                                style: '__builtInStyle5',
                            },
                            5: {
                                value: '变更后总金额',
                                style: '__builtInStyle5',
                            },
                            6: {
                                style: '__builtInStyle14',
                            },
                            7: {
                                style: '__builtInStyle14',
                            },
                            8: {
                                style: '__builtInStyle14',
                            },
                        },
                        6: {
                            0: {
                                value: '[支表2-中期支付证书.清单号]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle12',
                                },
                                bindingPath:
                                    'Ipes_MP_Certificate_DetailCalc.itemno',
                                tag: '{"instanceId":"dm8ne76xzvarj3lz1bzu4d7dpmptagm3glvw1b656","bindInfo":{"bindType":"cell","bindDsInstanceId":"itemno"}}',
                            },
                            1: {
                                style: '__builtInStyle13',
                            },
                            2: {
                                value: '[支表2-中期支付证书.项目内容]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath:
                                    'Ipes_MP_Certificate_DetailCalc.itemname',
                                tag: '{"instanceId":"vr5vt8ctlbhi38xm49maaszlhy1dov0v8lvw1b8s4","bindInfo":{"bindType":"cell","bindDsInstanceId":"itemname"}}',
                            },
                            3: {
                                value: '[支表2-中期支付证书.原有总金额]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath: 'Ipes_MP_Certificate_DetailCalc.htamt',
                                tag: '{"instanceId":"4eb456l6qjckwo93i3vszbo7z7w9df4lvw1bexe","bindInfo":{"bindType":"cell","bindDsInstanceId":"htamt"}}',
                            },
                            4: {
                                value: '[支表2-中期支付证书.变更总金额]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath: 'Ipes_MP_Certificate_DetailCalc.bgamt',
                                tag: '{"instanceId":"al6x3xyx92qkkkk7zcgcwhw6ikvtx8xzslvw1bi23","bindInfo":{"bindType":"cell","bindDsInstanceId":"bgamt"}}',
                            },
                            5: {
                                value: '[支表2-中期支付证书.变更后总金额]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath:
                                    'Ipes_MP_Certificate_DetailCalc.bghamt',
                                tag: '{"instanceId":"a8bjfllqe4637o0tivnb645cv67vgkphlvw1blsi","bindInfo":{"bindType":"cell","bindDsInstanceId":"bghamt"}}',
                            },
                            6: {
                                value: '[支表2-中期支付证书.本期末金额]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath:
                                    'Ipes_MP_Certificate_DetailCalc.bqmamt',
                                tag: '{"instanceId":"zelkazysqgphekntsvvd90bpoqnw0orlvw1bqwa","bindInfo":{"bindType":"cell","bindDsInstanceId":"bqmamt"}}',
                            },
                            7: {
                                value: '[支表2-中期支付证书.上期末金额]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath:
                                    'Ipes_MP_Certificate_DetailCalc.sqmamt',
                                tag: '{"instanceId":"u5ngr7dfvfssfyt179va5jkg3j339ndkklvw1bw16","bindInfo":{"bindType":"cell","bindDsInstanceId":"sqmamt"}}',
                            },
                            8: {
                                value: '[支表2-中期支付证书.本期金额]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle7',
                                },
                                bindingPath: 'Ipes_MP_Certificate_DetailCalc.bqamt',
                                tag: '{"instanceId":"77ywopxqcstqkn86gn9224p94jes51j4lvw1bztv","bindInfo":{"bindType":"cell","bindDsInstanceId":"bqamt"}}',
                            },
                        },
                        7: {
                            0: {
                                value: '承包商：',
                                style: '__builtInStyle8',
                            },
                            1: {
                                value: '[合同参数计算器.乙方公司]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle10',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_partybEnterprise',
                                tag: '{"instanceId":"7jdzmlh5ye9wy7m48wyfe0vbajivdcdzblvw1ci16","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_partybEnterprise"}}',
                            },
                            2: {
                                style: '__builtInStyle10',
                            },
                            3: {
                                value: '监理：',
                                style: '__builtInStyle8',
                            },
                            4: {
                                value: '[合同参数计算器.监查经理]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle10',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_supervisorManager',
                                tag: '{"instanceId":"4csad8jcpansr0zp12ptrqo7vzk9yc0rdlvw1cr6y","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_supervisorManager"}}',
                            },
                            5: {
                                style: '__builtInStyle10',
                            },
                            6: {
                                value: '业主：',
                                style: '__builtInStyle8',
                            },
                            7: {
                                value: '[合同参数计算器.乙方公司]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle10',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_partybEnterprise',
                                tag: '{"instanceId":"zmzpqxre0fcbhslyfd9ztxnx1qx8zbpelvw1djrm","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_partybEnterprise"}}',
                            },
                            8: {
                                style: '__builtInStyle10',
                            },
                        },
                        8: {
                            0: {
                                value: '日期：',
                                style: '__builtInStyle8',
                            },
                            1: {
                                value: '[合同参数计算器.实际开发日期]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle11',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_factStartDate',
                                tag: '{"instanceId":"im4rbuz0nk67bwup07cunulgzqpfusmlvw1dc90","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_factStartDate"}}',
                            },
                            2: {
                                style: '__builtInStyle11',
                            },
                            3: {
                                value: '日期：',
                                style: '__builtInStyle8',
                            },
                            4: {
                                value: '[合同参数计算器.实际开发日期]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle11',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_factStartDate',
                                tag: '{"instanceId":"mjxcola4x2keoau8vilvpa89ktkgw81bklvw1ddjx","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_factStartDate"}}',
                            },
                            5: {
                                style: '__builtInStyle11',
                            },
                            6: {
                                value: '日期：',
                                style: '__builtInStyle6',
                            },
                            7: {
                                value: '[合同参数计算器.实际开发日期]',
                                style: {
                                    cellType: {
                                        allowOverflow: true,
                                        typeName: '1',
                                        editorType: 1,
                                    },
                                    parentName: '__builtInStyle11',
                                },
                                bindingPath:
                                    'IP_Contract_ParamCalc.contract_factStartDate',
                                tag: '{"instanceId":"nuls1k7rvc84d4867qawqc6g3q6yz8679lvw1dfrf","bindInfo":{"bindType":"cell","bindDsInstanceId":"contract_factStartDate"}}',
                            },
                            8: {
                                style: '__builtInStyle11',
                            },
                        },
                    },
                    rowDataArray: [
                        null,
                        null,
                        null,
                        null,
                        {
                            style: '__builtInStyle4',
                        },
                        {
                            style: '__builtInStyle4',
                        },
                    ],
                    defaultDataNode: {
                        style: {
                            backColor: null,
                            foreColor: null,
                            vAlign: 2,
                            font: 'normal normal 13.3333px Arial',
                            borderLeft: null,
                            borderTop: null,
                            borderRight: null,
                            borderBottom: null,
                            locked: true,
                            textIndent: 0,
                            wordWrap: false,
                            shrinkToFit: false,
                            textDecoration: 0,
                            diagonalDown: null,
                            diagonalUp: null,
                            textOrientation: 0,
                            fontStyle: null,
                            fontWeight: null,
                            fontSize: '13.3333px',
                            fontFamily: 'Arial',
                            fontForColumnWidth: 'normal normal 13.3333px Arial',
                        },
                        tag: '{"instanceId":"qchru1hw6ua2iwb8sh603ej0pkp2psniqlvw1dtsw","pageArea":"7:7","isFillData":false}',
                    },
                },
                rowHeaderData: {
                    defaultDataNode: {
                        style: {
                            themeFont: 'Body',
                        },
                    },
                },
                colHeaderData: {
                    defaultDataNode: {
                        style: {
                            themeFont: 'Body',
                        },
                    },
                },
                rows: [
                    {
                        size: 45,
                    },
                    {
                        size: 45,
                    },
                    {
                        size: 27,
                    },
                    {
                        size: 27,
                    },
                    {
                        size: 20,
                    },
                    {
                        size: 20,
                    },
                    {
                        size: 17,
                    },
                    {
                        size: 17,
                    },
                    {
                        size: 17,
                    },
                ],
                columns: [
                    {
                        size: 58,
                    },
                    {
                        size: 34,
                    },
                    {
                        size: 208,
                    },
                    {
                        size: 106,
                    },
                    {
                        size: 106,
                    },
                    {
                        size: 106,
                    },
                    {
                        size: 106,
                    },
                    {
                        size: 106,
                    },
                    {
                        size: 106,
                    },
                ],
                defaultData: {},
                leftCellIndex: 0,
                topCellIndex: 0,
                spans: [
                    {
                        row: 4,
                        col: 7,
                        rowCount: 2,
                        colCount: 1,
                    },
                    {
                        row: 4,
                        col: 8,
                        rowCount: 2,
                        colCount: 1,
                    },
                    {
                        row: 3,
                        col: 7,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 7,
                        col: 7,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 8,
                        col: 7,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 2,
                        col: 1,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 3,
                        col: 1,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 2,
                        col: 4,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 0,
                        col: 0,
                        rowCount: 1,
                        colCount: 9,
                    },
                    {
                        row: 1,
                        col: 0,
                        rowCount: 1,
                        colCount: 9,
                    },
                    {
                        row: 4,
                        col: 3,
                        rowCount: 1,
                        colCount: 3,
                    },
                    {
                        row: 4,
                        col: 6,
                        rowCount: 2,
                        colCount: 1,
                    },
                    {
                        row: 3,
                        col: 4,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 4,
                        col: 0,
                        rowCount: 2,
                        colCount: 2,
                    },
                    {
                        row: 4,
                        col: 2,
                        rowCount: 2,
                        colCount: 1,
                    },
                    {
                        row: 7,
                        col: 1,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 8,
                        col: 1,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 7,
                        col: 4,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 8,
                        col: 4,
                        rowCount: 1,
                        colCount: 2,
                    },
                    {
                        row: 6,
                        col: 0,
                        rowCount: 1,
                        colCount: 2,
                    },
                ],
                selections: {
                    0: {
                        row: 0,
                        col: 0,
                        rowCount: 1,
                        colCount: 9,
                    },
                    length: 1,
                },
                defaults: {
                    colHeaderRowHeight: 20,
                    colWidth: 63,
                    rowHeaderColWidth: 40,
                    rowHeight: 17,
                },
                rowOutlines: {
                    items: [],
                },
                columnOutlines: {
                    items: [],
                },
                cellStates: {},
                states: {},
                outlineColumnOptions: {},
                autoMergeRangeInfos: [],
                printInfo: {
                    margin: {
                        top: 75,
                        bottom: 58,
                        left: 58,
                        right: 58,
                        header: 50,
                        footer: 50,
                    },
                    orientation: 2,
                    pageOrder: 1,
                    paperSize: {
                        width: 826.7716535433073,
                        height: 1169.2913385826773,
                        kind: 9,
                    },
                },
                rowHeaderVisible: false,
                colHeaderVisible: false,
                gridline: {
                    showHorizontalGridline: false,
                    showVerticalGridline: false,
                },
                index: 0,
                order: 0,
            },
        },
        sheetTabCount: 0,
        namedStyles: [
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 2,
                font: 'normal normal 13.3333px Arial',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: 'Normal',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '13.3333px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 2,
                font: 'normal normal 13.3333px Arial',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle1',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '13.3333px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 1,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle2',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 2,
                font: 'normal normal 10.6667px Arial',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle3',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 2,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle4',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 1,
                vAlign: 1,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: {
                    color: '#000000',
                    style: 1,
                },
                borderTop: {
                    color: '#000000',
                    style: 1,
                },
                borderRight: {
                    color: '#000000',
                    style: 1,
                },
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle5',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 2,
                vAlign: 2,
                font: 'normal normal 10.6667px 微软雅黑',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle6',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '微软雅黑',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 2,
                font: 'normal normal 13.3333px Arial',
                formatter: 'General',
                borderLeft: {
                    color: '#000000',
                    style: 1,
                },
                borderTop: {
                    color: '#000000',
                    style: 1,
                },
                borderRight: {
                    color: '#000000',
                    style: 1,
                },
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle7',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '13.3333px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 2,
                vAlign: 2,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle8',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 3,
                vAlign: 1,
                font: 'normal bold 24px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle9',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: 'bold',
                fontSize: '24px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 0,
                vAlign: 2,
                font: 'normal normal 10.6667px Arial',
                formatter: 'General',
                borderLeft: null,
                borderTop: {
                    color: '#000000',
                    style: 1,
                },
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle10',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 0,
                vAlign: 2,
                font: 'normal normal 10.6667px Arial',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle11',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 1,
                vAlign: 2,
                font: 'normal normal 13.3333px Arial',
                formatter: 'General',
                borderLeft: {
                    color: '#000000',
                    style: 1,
                },
                borderTop: {
                    color: '#000000',
                    style: 1,
                },
                borderRight: null,
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle12',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '13.3333px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 1,
                vAlign: 2,
                font: 'normal normal 13.3333px Arial',
                formatter: 'General',
                borderLeft: null,
                borderTop: {
                    color: '#000000',
                    style: 1,
                },
                borderRight: {
                    color: '#000000',
                    style: 1,
                },
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle13',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '13.3333px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 1,
                vAlign: 1,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: {
                    color: '#000000',
                    style: 1,
                },
                borderTop: {
                    color: '#000000',
                    style: 1,
                },
                borderRight: {
                    color: '#000000',
                    style: 1,
                },
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle14',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 0,
                vAlign: 2,
                font: 'normal normal 10.6667px Arial',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle15',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: 'Arial',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 0,
                vAlign: 1,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle16',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 0,
                vAlign: 1,
                font: 'normal normal 10.6667px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: {
                    color: '#000000',
                    style: 1,
                },
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle17',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: null,
                fontSize: '10.6667px',
                fontFamily: '宋体',
            },
            {
                backColor: null,
                foreColor: null,
                hAlign: 1,
                vAlign: 1,
                font: 'normal bold 24px 宋体',
                formatter: 'General',
                borderLeft: null,
                borderTop: null,
                borderRight: null,
                borderBottom: null,
                locked: true,
                textIndent: 0,
                wordWrap: false,
                shrinkToFit: false,
                textDecoration: 0,
                name: '__builtInStyle18',
                diagonalDown: null,
                diagonalUp: null,
                textOrientation: 0,
                fontStyle: null,
                fontWeight: 'bold',
                fontSize: '24px',
                fontFamily: '宋体',
            },
        ],
        namedPatterns: {},
    },
    datas:{
        IP_ContPeriods_ParamCalc: [
            {
                contPeriods_startDate: 1705680000000,
                contPeriods_chineseEndDateStr: '二〇二四年一月二十五日',
                contPeriods_yearMonth_YYYY_MM: '2024-01',
                contPeriods_startDateStr: '2024年1月20日',
                contPeriods_contPeriodsName: '计量期号：第1期[2024 年1 月]',
                contPeriods_yearMonth: '202401',
                contPeriods_name: '第1期',
                contPeriods_sequence: 1,
                contPeriods_contPeriodsCode: '2024-01-1',
                contPeriods_endDateStr: '2024年1月25日',
                contPeriods_yearMonthStr: '2024年01月',
                contPeriods_monthx: 1,
                contPeriods_refundBlj: false,
                contPeriods_type: 'COMMON_PERIODS',
                contPeriods_yearx: 2024,
                contPeriods_id: 'b922f05b10cb48479e1d219962dd88f8',
                contPeriods_projId: '0bf6fb6cec1343b6965525b5cc54a13b',
                contPeriods_reference: false,
                contPeriods_yearMonth_YYYYMM: '202401',
                contPeriods_yearMonth_YYYY_MMChinese: '2024年01月',
                contPeriods_finish: false,
                contPeriods_locked: false,
                contPeriods_contractId: 'c6bd7767ef354aa0871cc794f73ae84d',
                contPeriods_sequenceStr: '01',
                contPeriods_endDate: 1706112000000,
                contPeriods_class:
                    'com.toone.report.calculator.ipes.business.model.ContPeriods',
            },
        ],
        IP_Contract_ParamCalc: [
            {
                contract_ckkMaxMoney: 0.0,
                contract_partybEnterprise: '中国建筑股份有限公司',
                contract_endPeg: '',
                contract_id: 'c6bd7767ef354aa0871cc794f73ae84d',
                contract_dyyfkDetainTotalMoney: 2.0e7,
                contract_location: '',
                contract_clyfkPercent: 70.0,
                contract_projManager: '',
                contract_foreignCurrencyProportion: '',
                contract_engName: '',
                contract_code: 'AXGS-QL-01',
                contract_contractMonth: 24,
                contract_bljCode: '',
                contract_workerPayRate: 0.0,
                contract_billMoney: 8.12896986e8,
                contract_chiefEngineer: '',
                contract_clyfkMaxMoney: 0.0,
                contract_bljDetainPercent: 10.0,
                contract_signDate: 1705248000000,
                contract_bankAccount: '',
                contract_validContractMoney: '',
                contract_projId: '0bf6fb6cec1343b6965525b5cc54a13b',
                contract_owerLimitMoney: 0.0,
                contract_planStartDate: 1705680000000,
                contract_bank: '',
                contract_contractName: '安兴高速项目路面工程第一标段一项目经理部',
                contract_updateUserId: '',
                contract_dayworkLaborMoney: 0.0,
                contract_pegLength: 0.0,
                contract_type: 'CONTRACT_TYPE_SG',
                contract_dyyfkDetainPercent: 2.0,
                contract_ownerEnterprise: 'liuyf交通投资建设有限公司  ',
                contract_bljDetainMaxMoney: 0.0,
                contract_workerBank: '',
                contract_partycEnterprise: '',
                contract_dyyfkDetainMiniMoney: 2000000.0,
                contract_interimMoney: 0.0,
                contract_jlFlPercent: 0.0,
                contract_supervisorManager: '',
                contract_engPartybName: '',
                contract_labDirector: '',
                contract_hyjMaxMoney: 0.0,
                contract_pegName: '',
                contract_factStartDate: '',
                contract_planTotalWorkDays: 0,
                contract_clyfkDetainBeginPeriod: 2,
                contract_supervisorEnterprise: '广东华路交通科技有限公司',
                contract_clyfkDetainPartitionPeriod: 2,
                contract_workerBankAccount: '',
                contract_mainSubType: 0,
                contract_roadLevel: '',
                contract_workerPartybEnterprise: '',
                contract_foreignCurrencyType: '',
                contract_locked: false,
                contract_typeName: '施工合同',
                contract_bljDetainMiniMoney: 0.0,
                contract_class:
                    'com.toone.report.calculator.ipes.business.model.Contract',
                contract_clyfkDetainPercent: 100.0,
                contract_totalMoney: 1.054e9,
                contract_bidOpenDate: '',
                contract_partybManager: '张三',
                contract_verifymark: false,
                contract_name: '安兴高速项目路面工程第一标段一项目经理部',
                contract_factEndDate: '',
                contract_ckkPercent: 0.0,
                contract_foreignCurrencyExchangeRate: 0.0,
                contract_mainJobContents: '',
                contract_chineseTotalMoney: '壹拾亿零伍仟肆佰万元',
                contract_sortOrder: 5,
                contract_settlementCode: '',
                contract_beginPeg: '',
                contract_clauseCode: 'test',
                contract_name2: '安兴高速项目路面工程第一标段一项目经理部',
                contract_roadWays: 0,
                contract_planEndDate: 1768838400000,
                contract_spjMaxMoney: 0.0,
                contract_dyyfkTotalMoney: 6.33609626e7,
                contract_shortName: '安兴第一标段',
            },
        ],
        IP_Project_ParamCalc: [
            {
                project_updateUserId: '',
                project_name2: 'liuyf测试项目',
                project_planStartDate: 1706112000000,
                project_sysName: '',
                project_code: 'liuyf_test',
                project_updateTime: '',
                project_engCorporation: '',
                project_name: 'liuyf测试项目',
                project_engName: '',
                project_investment: 10000.0,
                project_factEndDate: '',
                project_subsidiaryId: '',
                project_id: '0bf6fb6cec1343b6965525b5cc54a13b',
                project_factStartDate: '',
                project_planEndDate: 1769270400000,
                project_registryDate: '',
                project_summary: '',
                project_subsidiaryName: '',
                project_class:
                    'com.toone.report.calculator.ipes.business.model.Project',
                project_corporation: 'liuyf交通投资建设有限公司1',
            },
        ],
        Ipes_MP_Certificate_DetailCalc: [
            {
                dataIndex: 1,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '200',
                itemname: '矿山开拓工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 2,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '100',
                itemname: '总则 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 3,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '300',
                itemname: '道路及附属工程',
                htamt: 6.55954636e8,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 1346506.63,
                sqmamt: 0.0,
                bqamt: 1346506.63,
            },
            {
                dataIndex: 4,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '400',
                itemname: '桥涵工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 5,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '500',
                itemname: '生产线工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 6,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '600',
                itemname: '建筑工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 7,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '700',
                itemname: '绿化工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 8,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '800',
                itemname: '机电工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 9,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '暂计款 ',
                itemname: '暂计款 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 10,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '优化分成',
                itemname: '优化分成',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 11,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '300-1',
                itemname: '300章 路面工程',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 12,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '清单小计（涉及暂扣项小计） ',
                itemname: '清单小计（涉及暂扣项小计） ',
                htamt: 6.55954636e8,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 1346506.63,
                sqmamt: 0.0,
                bqamt: 1346506.63,
            },
            {
                dataIndex: 13,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '暂列金额',
                itemname: '暂列金额',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 14,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '设计费',
                itemname: '设计费',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 15,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '清单计量小计',
                itemname: '清单计量小计',
                htamt: 6.55954636e8,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 1346506.63,
                sqmamt: 0.0,
                bqamt: 1346506.63,
            },
            {
                dataIndex: 16,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '价格调整',
                itemname: '价格调整',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 17,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '索赔金额 ',
                itemname: '索赔金额 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 18,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '违约罚金',
                itemname: '违约罚金',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 19,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '迟付款利息 ',
                itemname: '迟付款利息 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 20,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '奖罚金',
                itemname: '奖罚金',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 21,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '甲供材扣回',
                itemname: '甲供材扣回',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 22,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '合计',
                itemname: '合计',
                htamt: 6.55954636e8,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 1346506.63,
                sqmamt: 0.0,
                bqamt: 1346506.63,
            },
            {
                dataIndex: 23,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '开工预付款 ',
                itemname: '开工预付款 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 2.090911766e7,
                sqmamt: 0.0,
                bqamt: 2.090911766e7,
            },
            {
                dataIndex: 24,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '预付款扣款 ',
                itemname: '预付款扣款 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 25,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '计量暂扣款',
                itemname: '计量暂扣款',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 26,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '质量保证金 ',
                itemname: '质量保证金 ',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 27,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '返还计量暂扣款',
                itemname: '返还计量暂扣款',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 28,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '甲供材扣回',
                itemname: '甲供材扣回',
                htamt: 0.0,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 0.0,
                sqmamt: 0.0,
                bqamt: 0.0,
            },
            {
                dataIndex: 29,
                emptyRow: false,
                groupId: '',
                totalRow: false,
                yy: null,
                itemno: '实际支付',
                itemname: '实际支付',
                htamt: 6.55954636e8,
                bgamt: 0.0,
                bghamt: 0.0,
                bqmamt: 2.225562429e7,
                sqmamt: 0.0,
                bqamt: 2.225562429e7,
            },
        ],
    },
    test:``
}