import BaseIcon from '../base/BaseIcon';

/**
 * 合并单元格
 * @param {} props 
 * @returns 
 */
export default function (props) {
    return (
        <BaseIcon
            {...props}
            type='toone'
            icon='url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAYAAAA8AXHiAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAGaSURBVHic7dyxjQIxEEBRQJQAlWw7W961s5VADxCRIKG7wN8H4r0CPBt8ORhpvdsBAAAAAAAAAAAAAMB72o8+cFmW2+gz6W3bNrSFw8jD4EFYJIRFQlgkhEVCWCSEReI4e+Dofcmz3/Zo9fxX/vu7Zu8X3VgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVi+G/d5/XqqcgPdPk5eSqS9ycsEsIiISwSwiIhLBLCIjH9qcjR+xL+ZvZ+0Y1FQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSERUJYJIRFQlgkhEVCWCSOswee1+tt9kzmc2OREBYJYZEQFglhkRAWCWEBAAAAAAAAAAAAAABf5Q7noxs9D0sdJwAAAABJRU5ErkJggg==)'
        ></BaseIcon>
    );
}
