import BaseIcon from '../base/BaseIcon';

/**
 * 取消合并
 * @param {} props 
 * @returns 
 */
export default function (props) {
    return (
        <BaseIcon
            {...props}
            type='toone'
            icon='url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAYAAAA8AXHiAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAG2SURBVHic7dyxTQQxFEDBO0QJkJITuwiaoDzacUxOCj0cEclJp038dhHMFPDt4MmBJft0AgAAAAAAAAAAAACA3+m8euAY47J6Jr0559IW7lYOgx/CIiEsEsIiISwSwiIhLBL3ey+4+r7k2tY9Wr3+LUfva+/7RScWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGR2P2J/ePrV/rU+2Nr/efTIV9ZHr6v95d0/DUnFglhkRAWCWGREBYJYZEQFond77E+3x7SLxG37snq9W85el9PvorkLxAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBaJ8+qBY4zL6pn05pxLW3BikRAWCWGREBYJYZEQFglhAQAAAAAAAAAAAAAA/8o3HEsnwHLtaakAAAAASUVORK5CYII=)'
        ></BaseIcon>
    );
}
